packages:
  - ./
  - ./playground
  - ./backend
  - ./widget
catalogs:
  bundle:
    '@rollup/plugin-replace': ^6.0.2
    '@vitejs/plugin-vue': ^5.2.4
    vite: ^6.3.5
    vite-plugin-vue-devtools: ^7.7.6
  frontend:
    reka-ui: ^2.2.1
    vue: ^3.5.14
  lint:
    '@antfu/eslint-config': ^4.13.1
    '@nuxt/eslint': 1.4.0
    eslint: ^9.27.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0
  nuxt:
    '@nuxt/fonts': 0.11.4
    '@nuxt/image': 1.10.0
    '@vueuse/nuxt': ^13.2.0
    nuxt: ^3.17.3
  server:
    '@nuxthub/core': ^0.8.27
    '@octokit/rest': ^21.1.1
    drizzle-kit: ^0.31.1
    drizzle-orm: ^0.43.1
    valibot: ^1.1.0
    wrangler: ^4.16.0
  types:
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^22.15.19
    '@vue/tsconfig': ^0.7.0
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  unocss:
    '@iconify/utils': ^2.3.0
    '@unocss/eslint-plugin': ^66.1.2
    nimiq-css: ^1.0.0-beta.30
    unocss: ^66.1.2
    unocss-preset-onmax: ^1.0.0-beta.25
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - vue-demi
  - workerd
