packages:
  - ./
  - ./backend
  - ./widget

catalog:
  eslint-plugin-pnpm: ^1.1.2
  eslint-plugin-pnpm-catalog: ^0.0.1
  nimiq-icons: 1.0.0-beta.100
  nuxt-safe-runtime-config: ^0.0.3

catalogs:
  bundle:
    '@rollup/plugin-replace': ^6.0.2
    '@vitejs/plugin-vue': ^6.0.1
    vite: ^7.1.7
    vite-plugin-vue-devtools: ^8.0.2
  cli:
    pncat: ^0.5.4
  dev:
    '@nuxt/scripts': ^0.11.13
  frontend:
    reka-ui: 2.5.0
    vue: ^3.5.21
  lint:
    '@antfu/eslint-config': ^5.4.1
    '@nuxt/eslint': 1.9.0
    eslint: ^9.36.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.0
    simple-git-hooks: ^2.13.1
  node:
    consola: ^3.4.2
  nuxt:
    '@nuxt/fonts': ^0.11.4
    '@nuxt/image': ^1.11.0
    '@vueuse/nuxt': ^13.9.0
    nuxt: 4.1.2
  server:
    '@nuxthub/core': ^0.9.0
    '@octokit/rest': ^22.0.0
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.5
    valibot: ^1.1.0
    wrangler: ^4.39.0
  style:
    '@unocss/nuxt': ^66.5.2
  tools:
    '@antfu/ni': ^26.0.1
  types:
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^24.5.2
    '@vue/tsconfig': ^0.8.1
    typescript: ^5.9.2
    vue-tsc: ^3.0.8
  unocss:
    '@iconify/utils': ^3.0.2
    '@unocss/eslint-plugin': ^66.5.2
    nimiq-css: 1.0.0-beta.100
    unocss: ^66.5.2
    unocss-preset-onmax: 1.0.0-beta.43
  utils:
    '@vueuse/core': ^13.9.0

ignoredBuiltDependencies:
  - pncat

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
  - workerd
