packages:
  - ./
  - ./backend
  - ./widget
catalog:
  eslint-plugin-pnpm: ^1.1.1
  eslint-plugin-pnpm-catalog: ^0.0.1
  nimiq-icons: 1.0.0-beta.76
  nuxt-safe-runtime-config: ^0.0.3
catalogs:
  bundle:
    '@rollup/plugin-replace': ^6.0.2
    '@vitejs/plugin-vue': ^6.0.1
    vite: ^6.3.6
    vite-plugin-vue-devtools: ^8.0.1
  cli:
    pncat: ^0.5.4
  dev:
    '@nuxt/scripts': ^0.11.13
  frontend:
    reka-ui: ^2.5.0
    vue: ^3.5.21
  lint:
    '@antfu/eslint-config': ^5.3.0
    '@nuxt/eslint': 1.9.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
  node:
    consola: ^3.4.2
  nuxt:
    '@nuxt/fonts': ^0.11.4
    '@nuxt/image': ^1.11.0
    '@vueuse/nuxt': ^13.9.0
    # TODO: do not use 4.1.1. Wait for this to be resolved https://github.com/nuxt/ui/issues/4900
    nuxt: 4.1.0
  server:
    '@nuxthub/core': ^0.9.0
    '@octokit/rest': ^22.0.0
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.5
    valibot: ^1.1.0
    wrangler: ^4.35.0
  style:
    '@unocss/nuxt': ^66.5.1
  tools:
    '@antfu/ni': ^25.0.0
  types:
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^24.3.1
    '@vue/tsconfig': ^0.8.1
    typescript: ^5.9.2
    vue-tsc: ^3.0.6
  unocss:
    '@iconify/utils': ^3.0.1
    '@unocss/eslint-plugin': ^66.5.1
    nimiq-css: ^1.0.0-beta.76
    unocss: ^66.5.1
    unocss-preset-onmax: ^1.0.0-beta.37
  utils:
    '@vueuse/core': ^13.9.0
ignoredBuiltDependencies:
  - pncat
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
  - workerd
