packages:
  - ./
  - ./playground
catalog:
  '@rollup/plugin-replace': ^6.0.2
catalogs:
  bundle:
    '@vitejs/plugin-vue': ^5.2.3
    vite: ^6.2.4
    vite-plugin-vue-devtools: ^7.7.2
  frontend:
    '@vueuse/core': ^13.2.0
    reka-ui: ^2.2.1
    vue: ^3.5.13
    vue-router: ^4.5.1
  lint:
    '@antfu/eslint-config': ^4.13.0
    '@nuxt/eslint': 1.3.1
    eslint: ^9.26.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.0.0
    simple-git-hooks: ^2.13.0
  nuxt:
    '@nuxt/fonts': 0.11.3
    '@nuxt/image': 1.10.0
    '@vueuse/nuxt': ^13.2.0
    nuxt: ^3.17.3
  server:
    '@nuxthub/core': ^0.8.27
    '@octokit/rest': ^21.1.1
    drizzle-kit: ^0.31.1
    drizzle-orm: ^0.43.1
    valibot: ^1.1.0
    wrangler: ^4.14.4
  types:
    '@tsconfig/node22': ^22.0.1
    '@types/node': ^22.14.0
    '@vue/tsconfig': ^0.7.0
    typescript: ^5.8.3
    vue-tsc: ^2.2.8

  unocss:
    '@iconify/utils': ^2.3.0
    '@unocss/eslint-plugin': ^66.1.1
    '@unocss/nuxt': ^66.1.1
    '@unocss/reset': ^66.1.1
    nimiq-css: ^1.0.0-beta.22
    unocss: ^66.1.1
    unocss-preset-onmax: ^1.0.0-beta.19
    unocss-preset-scale-px: 1.0.0-beta.19
onlyBuiltDependencies:
  - sharp
  - simple-git-hooks
  - workerd
