packages:
  - ./
catalog:
  lint-staged: ^16.0.0
  simple-git-hooks: ^2.13.0
catalogs:
  frontend:
    '@vueuse/core': ^13.2.0
    vue: ^3.5.13
    vue-router: ^4.5.1
  lint:
    '@antfu/eslint-config': ^4.13.0
    '@nuxt/eslint': 1.3.1
    eslint: ^9.26.0
    eslint-plugin-format: ^1.0.1
  nuxt:
    '@nuxt/fonts': 0.11.3
    '@nuxt/image': 1.10.0
    '@vueuse/nuxt': ^13.2.0
    nuxt: ^3.17.3
  unocss:
    '@iconify/utils': ^2.3.0
    '@unocss/eslint-plugin': ^66.1.1
    '@unocss/nuxt': ^66.1.1
    '@unocss/reset': ^66.1.1
    nimiq-css: ^1.0.0-beta.22
    unocss: ^66.1.1
    unocss-preset-onmax: ^1.0.0-beta.19
    unocss-preset-scale-px: 1.0.0-beta.19
onlyBuiltDependencies:
  - simple-git-hooks
