name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: Deploy to NuxtHub
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          NUXT_GITHUB_OWNER: ${{ vars.NUXT_GITHUB_OWNER }}
          NUXT_GITHUB_REPO: ${{ vars.NUXT_GITHUB_REPO }}
          NUXT_PRODUCTION_URL: ${{ vars.NUXT_PRODUCTION_URL }}
          NUXT_GITHUB_TOKEN: ${{ secrets.NUXT_GITHUB_TOKEN }}
          NUXT_SLACK_WEBHOOK_URL: ${{ secrets.NUXT_SLACK_WEBHOOK_URL }}

      - name: Ensure NuxtHub module is installed
        run: pnpx nuxthub@latest ensure
        env:
          NUXT_GITHUB_OWNER: ${{ vars.NUXT_GITHUB_OWNER }}
          NUXT_GITHUB_REPO: ${{ vars.NUXT_GITHUB_REPO }}
          NUXT_PRODUCTION_URL: ${{ vars.NUXT_PRODUCTION_URL }}
          NUXT_GITHUB_TOKEN: ${{ secrets.NUXT_GITHUB_TOKEN }}
          NUXT_SLACK_WEBHOOK_URL: ${{ secrets.NUXT_SLACK_WEBHOOK_URL }}

      - name: Build application
        run: pnpm build
        env:
          NUXT_GITHUB_OWNER: ${{ vars.NUXT_GITHUB_OWNER }}
          NUXT_GITHUB_REPO: ${{ vars.NUXT_GITHUB_REPO }}
          NUXT_PRODUCTION_URL: ${{ vars.NUXT_PRODUCTION_URL }}
          NUXT_GITHUB_TOKEN: ${{ secrets.NUXT_GITHUB_TOKEN }}
          NUXT_SLACK_WEBHOOK_URL: ${{ secrets.NUXT_SLACK_WEBHOOK_URL }}

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: nq-feedback-4u0k
          directory: backend/dist
